services: 
  postgres: 
    image: postgres:17.4-alpine
    container_name: ${POSTGRES_HOST}
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - tp-data:/var/lib/postgresql/data
    ports: 
        - ${POSTGRES_PORT}:5432 

volumes: 
  tp-data:
    name: "tp-data"